# coding: utf-8

"""
    Uloq Requestor Service

    Requestor Endpoints  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from Eccenscia.Services.Models.configuration import Configuration


class PayloadObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'payload': 'str',
        'order': 'int'
    }

    attribute_map = {
        'payload': 'Payload',
        'order': 'Order'
    }

    def __init__(self, payload=None, order=None, local_vars_configuration=None):  # noqa: E501
        """PayloadObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._payload = None
        self._order = None
        self.discriminator = None

        if payload is not None:
            self.payload = payload
        if order is not None:
            self.order = order

    @property
    def payload(self):
        """Gets the payload of this PayloadObject.  # noqa: E501

        Base64 hashed BSSID from scan results.  # noqa: E501

        :return: The payload of this PayloadObject.  # noqa: E501
        :rtype: str
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this PayloadObject.

        Base64 hashed BSSID from scan results.  # noqa: E501

        :param payload: The payload of this PayloadObject.  # noqa: E501
        :type: str
        """

        self._payload = payload

    @property
    def order(self):
        """Gets the order of this PayloadObject.  # noqa: E501

        Unique order identifier. Used in the determination of the signature packet order  # noqa: E501

        :return: The order of this PayloadObject.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this PayloadObject.

        Unique order identifier. Used in the determination of the signature packet order  # noqa: E501

        :param order: The order of this PayloadObject.  # noqa: E501
        :type: int
        """

        self._order = order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PayloadObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PayloadObject):
            return True

        return self.to_dict() != other.to_dict()
