# coding: utf-8

"""
    Uloq Requestor Service

    Requestor Endpoints  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from Eccenscia.Services.Models.configuration import Configuration


class QRCodeResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'notification_identifier': 'str',
        'image': 'str',
        'url': 'str'
    }

    attribute_map = {
        'notification_identifier': 'NotificationIdentifier',
        'image': 'Image',
        'url': 'Url'
    }

    def __init__(self, notification_identifier=None, image=None, url=None, local_vars_configuration=None):  # noqa: E501
        """QRCodeResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._notification_identifier = None
        self._image = None
        self._url = None
        self.discriminator = None

        if notification_identifier is not None:
            self.notification_identifier = notification_identifier
        if image is not None:
            self.image = image
        if url is not None:
            self.url = url

    @property
    def notification_identifier(self):
        """Gets the notification_identifier of this QRCodeResponse.  # noqa: E501

        The notification identifier for the pending transaction. This identifier is used later to collect the response of the scan later.  # noqa: E501

        :return: The notification_identifier of this QRCodeResponse.  # noqa: E501
        :rtype: str
        """
        return self._notification_identifier

    @notification_identifier.setter
    def notification_identifier(self, notification_identifier):
        """Sets the notification_identifier of this QRCodeResponse.

        The notification identifier for the pending transaction. This identifier is used later to collect the response of the scan later.  # noqa: E501

        :param notification_identifier: The notification_identifier of this QRCodeResponse.  # noqa: E501
        :type: str
        """

        self._notification_identifier = notification_identifier

    @property
    def image(self):
        """Gets the image of this QRCodeResponse.  # noqa: E501

        The binary data in Base64 for the generated QR code  # noqa: E501

        :return: The image of this QRCodeResponse.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this QRCodeResponse.

        The binary data in Base64 for the generated QR code  # noqa: E501

        :param image: The image of this QRCodeResponse.  # noqa: E501
        :type: str
        """

        self._image = image

    @property
    def url(self):
        """Gets the url of this QRCodeResponse.  # noqa: E501

        The URL embedded in the QR code  # noqa: E501

        :return: The url of this QRCodeResponse.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this QRCodeResponse.

        The URL embedded in the QR code  # noqa: E501

        :param url: The url of this QRCodeResponse.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QRCodeResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QRCodeResponse):
            return True

        return self.to_dict() != other.to_dict()
